In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches[long].csv", index_col=0)

In [3]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,Match Report,NaN,13.0,1.0,17.8,0.0,0,0,2024,Liverpool
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,Match Report,NaN,25.0,9.0,16.8,1.0,0,1,2024,Liverpool
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,9.0,4.0,17.2,1.0,0,0,2024,Liverpool
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,Match Report,NaN,17.0,4.0,14.7,0.0,0,0,2024,Liverpool
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,Match Report,NaN,16.0,5.0,15.8,0.0,0,0,2024,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0.0,2.0,Aston Villa,...,Match Report,NaN,9.0,3.0,21.6,0.0,0,0,2022,Norwich City
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0.0,4.0,West Ham,...,Match Report,NaN,8.0,2.0,22.2,1.0,0,0,2022,Norwich City
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0.0,3.0,Leicester City,...,Match Report,NaN,9.0,5.0,17.0,0.0,0,0,2022,Norwich City
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1.0,1.0,Wolves,...,Match Report,NaN,11.0,2.0,14.4,0.0,0,0,2022,Norwich City
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0.0,5.0,Tottenham,...,Match Report,NaN,9.0,0.0,18.6,0.0,0,0,2022,Norwich City

In [205]:
matches[matches["team"]=="Arsenal"]

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,0.0,0,0,2024,Arsenal,1,18,12,5,1
2,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,0.0,1,1,2024,Arsenal,0,7,20,0,1
3,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,0.0,1,1,2024,Arsenal,1,9,15,5,0
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,0.0,0,0,2024,Arsenal,1,15,16,6,1
5,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,0.0,0,0,2024,Arsenal,0,8,16,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,2022-05-01,16:30,Premier League,Matchweek 35,Sun,Away,W,2.0,1.0,West Ham,...,0.0,0,0,2022,Arsenal,0,23,16,6,1
41,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,W,2.0,1.0,Leeds United,...,2.0,0,0,2022,Arsenal,1,10,14,6,1
42,2022-05-12,19:45,Premier League,Matchweek 22,Thu,Away,L,0.0,3.0,Tottenham,...,0.0,0,0,2022,Arsenal,0,21,19,3,0
43,2022-05-16,20:00,Premier League,Matchweek 37,Mon,Away,L,0.0,2.0,Newcastle Utd,...,0.0,0,0,2022,Arsenal,0,16,20,0,0
44,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,5.0,1.0,Everton,...,0.0,1,1,2022,Arsenal,1,8,16,6,1

In [5]:
matches["team"].value_counts()

West Ham United             107
Wolverhampton Wanderers     106
Everton                     106
Aston Villa                 106
Tottenham Hotspur           106
Brentford                   106
Newcastle United            106
Crystal Palace              106
Arsenal                     105
Liverpool                   105
Brighton and Hove Albion    105
Manchester United           105
Manchester City             105
Chelsea                     104
Southampton                  76
Leeds United                 76
Leicester City               76
Burnley                      69
Fulham                       69
Nottingham Forest            69
Bournemouth                  68
Watford                      38
Norwich City                 38
Luton Town                   30
Sheffield United             29
Name: team, dtype: int64

In [6]:
matches["round"].value_counts()

Matchweek 1     60
Matchweek 16    60
Matchweek 30    60
Matchweek 28    60
Matchweek 27    60
Matchweek 25    60
Matchweek 24    60
Matchweek 23    60
Matchweek 22    60
Matchweek 21    60
Matchweek 2     60
Matchweek 19    60
Matchweek 18    60
Matchweek 17    60
Matchweek 20    60
Matchweek 15    60
Matchweek 8     60
Matchweek 3     60
Matchweek 4     60
Matchweek 14    60
Matchweek 6     60
Matchweek 7     60
Matchweek 5     60
Matchweek 9     60
Matchweek 10    60
Matchweek 11    60
Matchweek 12    60
Matchweek 13    60
Matchweek 26    58
Matchweek 31    50
Matchweek 29    48
Matchweek 33    40
Matchweek 34    40
Matchweek 35    40
Matchweek 36    40
Matchweek 37    40
Matchweek 32    40
Matchweek 38    40
Name: round, dtype: int64

In [7]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [207]:
matches["date"] = pd.to_datetime(matches["date"])

In [210]:
matches[matches["team"]=="Arsenal", matches["date"].datetime.year() == 2023]

AttributeError: 'Series' object has no attribute 'datetime'

In [11]:
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
dtype: object

In [12]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [14]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [17]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [18]:
matches["day_code"] = matches["date"].dt.dayofweek

In [21]:
matches["target"] = (matches["result"] == "W").astype("int")

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [190]:
train = matches[matches["date"] < '2024-01-01']
test = matches[matches["date"] > '2024-01-01']
predictors = ["venue_code", "opp_code", "hour", "day_code"]
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [191]:
preds = rf.predict(test[predictors])

In [192]:
from sklearn.metrics import accuracy_score

In [193]:
acc = accuracy_score(test["target"], preds)

In [194]:
acc

0.6435643564356436

In [195]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds))

In [196]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction    0   1
actual
0           106  26
1            46  24

In [197]:
from sklearn.metrics import precision_score

In [198]:
precision_score(test["target"], preds)

0.48

In [199]:
grouped_matches = matches.groupby("team")

In [200]:
group = grouped_matches.get_group("Arsenal").sort_values("date")

In [167]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [168]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [169]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,...,5,1,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.000000,0.000000
5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,...,5,1,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.000000,0.000000
7,2021-09-26,16:30,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,Tottenham,...,6,1,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.000000,0.000000
8,2021-10-02,17:30,Premier League,Matchweek 7,Sat,Away,D,0.0,0.0,Brighton,...,5,0,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.000000,0.000000
9,2021-10-18,20:00,Premier League,Matchweek 8,Mon,Home,D,2.0,2.0,Crystal Palace,...,0,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,2024-02-17,15:00,Premier League,Matchweek 25,Sat,Away,W,5.0,0.0,Burnley,...,5,1,3.666667,0.666667,19.333333,7.000000,15.933333,0.000000,0.333333,0.333333
36,2024-02-24,20:00,Premier League,Matchweek 26,Sat,Home,W,4.0,1.0,Newcastle Utd,...,5,1,4.666667,0.333333,18.000000,8.000000,15.666667,0.333333,0.666667,0.666667
37,2024-03-04,20:00,Premier League,Matchweek 27,Mon,Away,W,6.0,0.0,Sheffield Utd,...,0,1,5.000000,0.333333,19.000000,8.000000,15.533333,0.333333,0.666667,0.666667
38,2024-03-09,17:30,Premier League,Matchweek 28,Sat,Home,W,2.0,1.0,Brentford,...,5,1,5.000000,0.333333,18.333333,7.333333,15.400000,0.666667,0.333333,0.333333
40,2024-03-31,16:30,Premier League,Matchweek 30,Sun,Away,D,0.0,0.0,Manchester City,...,6,0,4.000000,0.666667,19.000000,7.000000,15.266667,0.333333,0.000000,0.000000

In [170]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [171]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 4  2021-09-11  15:00  Premier League   Matchweek 4
                        5  2021-09-18  15:00  Premier League   Matchweek 5
                        7  2021-09-26  16:30  Premier League   Matchweek 6
                        8  2021-10-02  17:30  Premier League   Matchweek 7
                        9  2021-10-18  20:00  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 30 2024-02-25  13:30  Premier League  Matchweek 26
                        32 2024-03-02  15:00  Premier League  Matchweek 27
                        33 2024-03-09  15:00  Premier League  Matchweek 28
                        35 2024-03-30  17:30  Premier League  Matchweek 30
                        36 2024-04-02  19:45  Premier League  Matchweek 31

                            day venue result   gf   ga        opponent  ...  \
team                                                                    ...
Arsenal                 4   Sat  Home      W  1.0  0.0    Norwich City  ...
                        5   Sat  Away      W  1.0  0.0         Burnley  ...
                        7   Sun  Home      W  3.0  1.0       Tottenham  ...
                        8   Sat  Away      D  0.0  0.0        Brighton  ...
                        9   Mon  Home      D  2.0  2.0  Crystal Palace  ...
...                         ...   ...    ...  ...  ...             ...  ...
Wolverhampton Wanderers 30  Sun  Home      W  1.0  0.0   Sheffield Utd  ...
                        32  Sat  Away      L  0.0  3.0   Newcastle Utd  ...
                        33  Sat  Home      W  2.0  1.0          Fulham  ...
                        35  Sat  Away      L  0.0  2.0     Aston Villa  ...
                        36  Tue  Away      D  1.0  1.0         Burnley  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 4          5       1    0.000000    3.000000
                        5          5       1    0.333333    2.333333
                        7          6       1    0.666667    1.666667
                        8          5       0    1.666667    0.333333
                        9          0       0    1.333333    0.333333
...                              ...     ...         ...         ...
Wolverhampton Wanderers 30         6       1    2.000000    1.666667
                        32         5       0    1.000000    1.000000
                        33         5       1    1.000000    1.333333
                        35         5       0    1.000000    1.333333
                        36         1       0    0.666667    2.000000

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 4    9.666667    2.333333    14.833333   0.333333
                        5   12.333333    3.000000    14.133333   0.333333
                        7   14.666667    3.000000    14.800000   0.666667
                        8   18.333333    5.333333    18.433333   0.666667
                        9   11.000000    4.000000    19.833333   0.666667
...                               ...         ...          ...        ...
Wolverhampton Wanderers 30  14.000000    6.000000    16.566667   1.000000
                        32  14.000000    4.666667    15.900000   0.333333
                        33  12.333333    4.000000    15.466667   0.000000
                        35  11.000000    2.666667    15.600000   0.000000
                        36  11.000000    3.000000    15.600000   0.333333

                            pk_rolling  pkatt_rolling
team
Arsenal                 4     0.000000       0.000000
                        5     0.000000       0.000000
                        7     0.000000       0.000000
                        8     0.000000       0.000000
                        9     0.000000       0.000000
...                                ...            ...
Wolverhampton Wanderers 30    0.333333       0.333333
                        32    0.000000       0.000000
                        33    0.000000       0.000000
                        35    0.000000       0.000000
                        36    0.000000       0.000000

[2041 rows x 40 columns]

In [172]:
matches_rolling = matches_rolling.droplevel('team')
matches_rolling.index = range(matches_rolling.shape[0])

In [173]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,...,5,1,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.000000,0.000000
1,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,...,5,1,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.000000,0.000000
2,2021-09-26,16:30,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,Tottenham,...,6,1,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.000000,0.000000
3,2021-10-02,17:30,Premier League,Matchweek 7,Sat,Away,D,0.0,0.0,Brighton,...,5,0,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.000000,0.000000
4,2021-10-18,20:00,Premier League,Matchweek 8,Mon,Home,D,2.0,2.0,Crystal Palace,...,0,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2036,2024-02-25,13:30,Premier League,Matchweek 26,Sun,Home,W,1.0,0.0,Sheffield Utd,...,6,1,2.000000,1.666667,14.000000,6.000000,16.566667,1.000000,0.333333,0.333333
2037,2024-03-02,15:00,Premier League,Matchweek 27,Sat,Away,L,0.0,3.0,Newcastle Utd,...,5,0,1.000000,1.000000,14.000000,4.666667,15.900000,0.333333,0.000000,0.000000
2038,2024-03-09,15:00,Premier League,Matchweek 28,Sat,Home,W,2.0,1.0,Fulham,...,5,1,1.000000,1.333333,12.333333,4.000000,15.466667,0.000000,0.000000,0.000000
2039,2024-03-30,17:30,Premier League,Matchweek 30,Sat,Away,L,0.0,2.0,Aston Villa,...,5,0,1.000000,1.333333,11.000000,2.666667,15.600000,0.000000,0.000000,0.000000
2040,2024-04-02,19:45,Premier League,Matchweek 31,Tue,Away,D,1.0,1.0,Burnley,...,1,0,0.666667,2.000000,11.000000,3.000000,15.600000,0.333333,0.000000,0.000000

In [174]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2024-01-01']
    test = data[data["date"] > '2024-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], prediction=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [175]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [176]:
precision

0.6666666666666666

In [177]:
combined

      actual  prediction
93         1           1
94         1           1
95         1           1
96         1           1
97         1           1
...      ...         ...
2036       1           0
2037       0           0
2038       1           0
2039       0           0
2040       0           0

[202 rows x 2 columns]

In [178]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [179]:
combined

,actual,prediction,date,team,opponent,result
93,1,1,2024-01-20,Arsenal,Crystal Palace,W
94,1,1,2024-01-30,Arsenal,Nott'ham Forest,W
95,1,1,2024-02-04,Arsenal,Liverpool,W
96,1,1,2024-02-11,Arsenal,West Ham,W
97,1,1,2024-02-17,Arsenal,Burnley,W
...,...,...,...,...,...,...
2036,1,0,2024-02-25,Wolverhampton Wanderers,Sheffield Utd,W
2037,0,0,2024-03-02,Wolverhampton Wanderers,Newcastle Utd,L
2038,1,0,2024-03-09,Wolverhampton Wanderers,Fulham,W
2039,0,0,2024-03-30,Wolverhampton Wanderers,Aston Villa,L
2040,0,0,2024-04-02,Wolverhampton Wanderers,Burnley,D

In [180]:
class MissingDict(dict):
    __missing__ = lambda self, key: key
    
map_values = {"Brighton and Hove Albion": "Brighton", 
              "Manchester United": "Manchester Utd", 
              "Newcastle United": "Newcastle Utd", 
              "Tottenham Hotspur": "Tottenham", 
              "West Ham United": "West Ham", 
              "Wolverhampton Wanderers": "Wolves"} 

mapping = MissingDict(**map_values)

In [181]:
combined["new_team"] = combined["team"].map(mapping)

In [182]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [183]:
merged

,actual_x,prediction_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,prediction_y,team_y,opponent_y,result_y,new_team_y
0,1,1,2024-01-20,Arsenal,Crystal Palace,W,Arsenal,0,0,Crystal Palace,Arsenal,L,Crystal Palace
1,1,1,2024-01-30,Arsenal,Nott'ham Forest,W,Arsenal,0,0,Nottingham Forest,Arsenal,L,Nottingham Forest
2,1,1,2024-02-04,Arsenal,Liverpool,W,Arsenal,0,0,Liverpool,Arsenal,L,Liverpool
3,1,1,2024-02-11,Arsenal,West Ham,W,Arsenal,0,0,West Ham United,Arsenal,L,West Ham
4,1,1,2024-02-17,Arsenal,Burnley,W,Arsenal,0,0,Burnley,Arsenal,L,Burnley
...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,1,0,2024-02-25,Wolverhampton Wanderers,Sheffield Utd,W,Wolves,0,0,Sheffield United,Wolves,L,Sheffield United
178,0,0,2024-03-02,Wolverhampton Wanderers,Newcastle Utd,L,Wolves,1,1,Newcastle United,Wolves,W,Newcastle Utd
179,1,0,2024-03-09,Wolverhampton Wanderers,Fulham,W,Wolves,0,1,Fulham,Wolves,L,Fulham
180,0,0,2024-03-30,Wolverhampton Wanderers,Aston Villa,L,Wolves,1,0,Aston Villa,Wolves,W,Aston Villa
181,0,0,2024-04-02,Wolverhampton Wanderers,Burnley,D,Wolves,0,0,Burnley,Wolves,D,Burnley

In [184]:
merged[(merged["prediction_x"] == 1) & (merged["prediction_y"] == 0)]["actual_x"].value_counts()

1    43
0    19
Name: actual_x, dtype: int64

In [189]:
43/62

0.6935483870967742